# Generated by Django 5.1.4 on 2024-12-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpimexTradingResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_product_id', models.CharField(max_length=100)),
                ('exchange_product_name', models.CharField(max_length=255)),
                ('oil_id', models.CharField(max_length=100)),
                ('delivery_basis_id', models.CharField(max_length=100)),
                ('delivery_basis_name', models.CharField(max_length=255)),
                ('delivery_type_id', models.CharField(max_length=100)),
                ('volume', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
    ]
