# Generated by Django 5.1.4 on 2024-12-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spimex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spimextradingresults',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='delivery_basis_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='delivery_type_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='exchange_product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='oil_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spimextradingresults',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
